/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu.cetak;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Mr.Al
 */
public class MenuCetak extends javax.swing.JFrame {

    /**
     * Creates new form MenuCetak
     */
    public MenuCetak() {
        initComponents();
        this.setResizable(false);
    }



   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BTN_PEN = new javax.swing.JButton();
        BTN_PEM = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Cetak");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 780, 10));

        BTN_PEN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BTN_PEN.setText("CETAK LAPORAN PENJUALAN");
        BTN_PEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PENActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_PEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 310, 70));

        BTN_PEM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BTN_PEM.setText("CETAK LAPORAN PEMBELIAN");
        BTN_PEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PEMActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_PEM, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 310, 70));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FORM CETAK");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_PENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PENActionPerformed
        // TODO add your handling code here:
        CetakPenjualan cetak = new CetakPenjualan();
        cetak.setVisible(true);

    }//GEN-LAST:event_BTN_PENActionPerformed

    private void BTN_PEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PEMActionPerformed
        // TODO add your handling code here:
        CetakPembelian cetak = new CetakPembelian();
        cetak.setVisible(true);
    }//GEN-LAST:event_BTN_PEMActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_PEM;
    private javax.swing.JButton BTN_PEN;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
