/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import menu.cetak.CetakPenjualan;

/**
 *
 * @author Mr.Al
 */
public final class TampilanPenjualan extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public TampilanPenjualan() {
        initComponents();
        tampilData();
        JTA_Hasil.setEditable(false);
        this.setResizable(false);
    }

    private void baru() {
        BTN_Trs.setText("BATAL");
        BTN_SIM.setEnabled(true);
        BTN_UB.setEnabled(false);
        BTN_HAP.setEnabled(false);
        BTN_CET.setEnabled(false);

        BTN_HIT.setEnabled(true);
        BTN_BER.setEnabled(true);
        CB_KODE.setEnabled(true);
        CB_TGL.setEnabled(true);
        bersih();
    }

    private void batalbaru() {
        BTN_Trs.setText("Transaksi Baru");
        BTN_SIM.setEnabled(false);
        tomboloff();

    }

    void tomboloff() {
        BTN_HAP.setEnabled(false);
        BTN_UB.setEnabled(false);
        BTN_BER.setEnabled(false);
        BTN_CET.setEnabled(false);
        BTN_HIT.setEnabled(false);
        CB_KODE.setEnabled(false);
        CB_TGL.setEnabled(false);

    }

    void tombolon() {
        BTN_HAP.setEnabled(true);
        BTN_UB.setEnabled(true);
        BTN_BER.setEnabled(true);
        BTN_CET.setEnabled(true);

        CB_KODE.setEnabled(true);
        CB_TGL.setEnabled(true);
    }

    void bersih() {
        JT_JUMLAHBELI.setText("");
        JT_HARGABARANG.setText("");
        JT_TGL.setText("");
        this.txt_kode.setText("Kode");
        this.txtsub.setText("");
        JT_TRANSAKSI.setText("");
        jt_bayar.setText("");
        this.txtkembali.setText("");
        jt_total.setText("");
        JT_NAMABARANG.setText("");

        tampilData();
    }

    void tampilData() {
        DefaultTableModel table = new DefaultTableModel();

        table.addColumn("teransaksi");
        table.addColumn("tanggal");
        table.addColumn("kodebarang");
        table.addColumn("namabarang");
        table.addColumn("harga");
        table.addColumn("jumlahbeli");
        table.addColumn("total");
        table.addColumn("bayar");
        table.addColumn("kembalian");

        jTable1.setModel(table);

        try {
            koneksi kk = new koneksi();
            kk.koneksiDatabase();
            String querytampil = "select * from tbl_penjualan";

            ResultSet res = kk.state.executeQuery(querytampil);

            while (res.next()) {
                table.addRow(new Object[]{
                    res.getString("teransaksi"), res.getString("tanggal"), res.getString("kodebarang"), res.getString("namabarang"), res.getString("harga"), res.getString("jumlahbeli"), res.getString("total"), res.getString("bayar"), res.getString("kembalian")
                });
                jTable1.setModel(table);
            }
        } catch (SQLException e) {
            System.err.println("" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTN_BER = new javax.swing.JButton();
        BTN_UB = new javax.swing.JButton();
        BTN_SIM = new javax.swing.JButton();
        BTN_KEL = new javax.swing.JButton();
        BTN_HAP = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        BTN_CET = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BTN_Trs = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        JT_TGL = new javax.swing.JTextField();
        CB_TGL = new org.freixas.jcalendar.JCalendarCombo();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTA_Hasil = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtkembali = new javax.swing.JLabel();
        jt_bayar = new javax.swing.JTextField();
        txtsub = new javax.swing.JLabel();
        BTN_HIT = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        txtsub1 = new javax.swing.JLabel();
        txtkembali1 = new javax.swing.JLabel();
        CB_KODE = new javax.swing.JComboBox<>();
        txt_kode = new javax.swing.JLabel();
        JT_HARGABARANG = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        JT_TRANSAKSI = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jt_total = new javax.swing.JTextField();
        JT_JUMLAHBELI = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        JT_NAMABARANG = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Penjualan");
        setBackground(new java.awt.Color(0, 153, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTN_BER.setText("Bersih");
        BTN_BER.setEnabled(false);
        BTN_BER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BERActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_BER, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 90, -1));

        BTN_UB.setText("Ubah");
        BTN_UB.setEnabled(false);
        BTN_UB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_UBActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_UB, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 80, -1));

        BTN_SIM.setText("Simpan");
        BTN_SIM.setEnabled(false);
        BTN_SIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SIMActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_SIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 90, -1));

        BTN_KEL.setText("Keluar");
        BTN_KEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_KELActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_KEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 90, -1));

        BTN_HAP.setText("Hapus");
        BTN_HAP.setEnabled(false);
        BTN_HAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_HAPActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_HAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 90, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("TRANSAKSI PENJUALAN");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        BTN_CET.setText("CETAK");
        BTN_CET.setEnabled(false);
        BTN_CET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CETActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_CET, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 90, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 920, 10));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 620, 190));

        BTN_Trs.setText("Transaksi Baru");
        BTN_Trs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_TrsActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_Trs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, 30));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Tgl Transaksi");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 90, 23));

        JT_TGL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_TGLActionPerformed(evt);
            }
        });
        jPanel1.add(JT_TGL, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 170, 30));

        CB_TGL.setEnabled(false);
        CB_TGL.addDateListener(new org.freixas.jcalendar.DateListener() {
            public void dateChanged(org.freixas.jcalendar.DateEvent evt) {
                CB_TGLDateChanged(evt);
            }
        });
        CB_TGL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CB_TGLMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CB_TGLMousePressed(evt);
            }
        });
        CB_TGL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_TGLActionPerformed(evt);
            }
        });
        jPanel1.add(CB_TGL, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 70, 40, 30));

        JTA_Hasil.setColumns(20);
        JTA_Hasil.setRows(5);
        jScrollPane2.setViewportView(JTA_Hasil);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 240, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 320));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, 140));

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Bayar");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 63, 23));

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Kembali");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 63, 23));

        txtkembali.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtkembali.setForeground(new java.awt.Color(255, 255, 255));
        txtkembali.setText(".");
        jPanel3.add(txtkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 170, -1));

        jt_bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jt_bayarKeyReleased(evt);
            }
        });
        jPanel3.add(jt_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 160, -1));

        txtsub.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtsub.setForeground(new java.awt.Color(255, 255, 255));
        txtsub.setText(".");
        jPanel3.add(txtsub, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 150, -1));

        BTN_HIT.setText("Hitung");
        BTN_HIT.setEnabled(false);
        BTN_HIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_HITActionPerformed(evt);
            }
        });
        jPanel3.add(BTN_HIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, 70, 40));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Sub Total");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 63, 23));

        txtsub1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtsub1.setForeground(new java.awt.Color(255, 255, 255));
        txtsub1.setText("Rp");
        jPanel3.add(txtsub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 188, -1));

        txtkembali1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtkembali1.setForeground(new java.awt.Color(255, 255, 255));
        txtkembali1.setText("Rp");
        jPanel3.add(txtkembali1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 30, -1));

        CB_KODE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih kode barang", "1", "2", "3", "4", "5" }));
        CB_KODE.setEnabled(false);
        CB_KODE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_KODEActionPerformed(evt);
            }
        });
        jPanel3.add(CB_KODE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 110, -1));

        txt_kode.setForeground(new java.awt.Color(255, 255, 255));
        txt_kode.setText("Kode");
        jPanel3.add(txt_kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 30, 23));

        JT_HARGABARANG.setEditable(false);
        jPanel3.add(JT_HARGABARANG, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 112, -1));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("No Transaksi");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 23));

        JT_TRANSAKSI.setEnabled(false);
        JT_TRANSAKSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JT_TRANSAKSIActionPerformed(evt);
            }
        });
        JT_TRANSAKSI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JT_TRANSAKSIKeyPressed(evt);
            }
        });
        jPanel3.add(JT_TRANSAKSI, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 112, -1));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Harga");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 63, 23));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Jumlah");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 63, 23));

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Total Harga");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 90, 23));

        jt_total.setEditable(false);
        jPanel3.add(jt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 112, -1));

        JT_JUMLAHBELI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JT_JUMLAHBELIKeyReleased(evt);
            }
        });
        jPanel3.add(JT_JUMLAHBELI, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 64, -1));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Kode Barang");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 72, 23));
        jPanel3.add(JT_NAMABARANG, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 110, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama Barang");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 920, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_BERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BERActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_BTN_BERActionPerformed

    private void BTN_UBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_UBActionPerformed
        // TODO add your handling code here:
        int teransaksi = Integer.parseInt(JT_TRANSAKSI.getText());
        String tanggal = JT_TGL.getText();
        String kodebarang = txt_kode.getText();
        String namabarang = JT_NAMABARANG.getText();
        String harga = JT_HARGABARANG.getText();
        String jumlahbeli = JT_JUMLAHBELI.getText();

        String total = jt_total.getText();
        String bayar = jt_bayar.getText();
        String kembalian = txtkembali.getText();

        try {
            String queryUpdate = "Update tbl_penjualan set "
                    + "tanggal = ('" + tanggal + "'), "
                    + "kodebarang = ('" + kodebarang + "'), "
                    + "namabarang  = ('" + namabarang + "'), "
                    + "harga = ('" + harga + "'), "
                    + "jumlahbeli = ('" + jumlahbeli + "'), "
                    + "total= ('" + total + "'), "
                    + "bayar = ('" + bayar + "') "
                    + "where kembalian =('" + kembalian + "') ";
            koneksi cc = new koneksi();
            cc.koneksiDatabase();
            cc.state.executeUpdate(queryUpdate);

            JOptionPane.showMessageDialog(null, "Data Terupdate");
            tampilData();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Anda salah memasukan nilai");
        }
    }//GEN-LAST:event_BTN_UBActionPerformed

    private void BTN_SIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SIMActionPerformed
        // TODO add your handling code here:
        String tanggal = JT_TGL.getText();
        String kodebarang = this.txt_kode.getText();
        String namabarang = JT_NAMABARANG.getText();
        String harga = JT_HARGABARANG.getText();
        String jumlahbeli = JT_JUMLAHBELI.getText();
        String total = jt_total.getText();
        String bayar = jt_bayar.getText();
        String kembalian = this.txtkembali.getText();
        koneksi kk = new koneksi();
        kk.koneksiDatabase();
        try {
            String query = "insert into tbl_penjualan (tanggal, kodebarang, namabarang, harga, jumlahbeli, total, bayar, kembalian) Values "
                    + "('" + tanggal + "','" + kodebarang + "','" + namabarang + "','" + harga + "','" + jumlahbeli + "','" + total + "','" + bayar + "','" + kembalian + "')";
            kk.state.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            kk.connect.close();
            tampilData();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Anda salah memasukan nilai");
        }
        tampilData();
    }//GEN-LAST:event_BTN_SIMActionPerformed

    private void BTN_KELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_KELActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BTN_KELActionPerformed

    private void BTN_HAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_HAPActionPerformed
        // TODO add your handling code here:
        try {
            int pilih = JOptionPane.showConfirmDialog(null, "Apakah anda ingin menghapus data ini ? ");
            if (pilih == JOptionPane.OK_OPTION) {

                String teransaksi = JT_TRANSAKSI.getText();
                String queryhapus
                        = "delete from tbl_penjualan where teransaksi =('" + teransaksi + "')";
                koneksi cc = new koneksi();
                cc.koneksiDatabase();
                cc.state.executeUpdate(queryhapus);
                JOptionPane.showMessageDialog(null, "Data Terhapus");
                tampilData();
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Anda salah memasukan nilai");
        }
    }//GEN-LAST:event_BTN_HAPActionPerformed

    private void CB_KODEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_KODEActionPerformed
        // TODO add your handling code here:
        if (CB_KODE.getSelectedItem().equals("Pilih Kode Barang")) {
            txt_kode.setText("");
        } else if (CB_KODE.getSelectedItem().equals("1")) {
            txt_kode.setText("1");
            JT_NAMABARANG.setText("Baju Kaos");
            JT_HARGABARANG.setText("65000");

        } else if (CB_KODE.getSelectedItem().equals("2")) {
            txt_kode.setText("2");
            JT_NAMABARANG.setText(" Baju Kemeja");
            JT_HARGABARANG.setText("125000");
        } else if (CB_KODE.getSelectedItem().equals("3")) {
            txt_kode.setText("3");
            JT_NAMABARANG.setText("Sweater");
            JT_HARGABARANG.setText("125000");
        } else if (CB_KODE.getSelectedItem().equals("4")) {
            txt_kode.setText("4");
            JT_NAMABARANG.setText(" Jaket ");
            JT_HARGABARANG.setText("185000");
        } else if (CB_KODE.getSelectedItem().equals("5")) {
            txt_kode.setText("5");
            JT_NAMABARANG.setText(" Topi");
            JT_HARGABARANG.setText("35000");
        }

    }//GEN-LAST:event_CB_KODEActionPerformed

    private void JT_JUMLAHBELIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JT_JUMLAHBELIKeyReleased
        try {
            int harga = Integer.parseInt(JT_HARGABARANG.getText().trim());
            int jumlah = Integer.parseInt(JT_JUMLAHBELI.getText().trim());

            int total = harga * jumlah;

            jt_total.setText("" + total);
            txtsub.setText("" + total);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Anda salah memasukan");
        }
    }//GEN-LAST:event_JT_JUMLAHBELIKeyReleased

    private void JT_TRANSAKSIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JT_TRANSAKSIKeyPressed

    }//GEN-LAST:event_JT_TRANSAKSIKeyPressed

    private void jt_bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_bayarKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jt_bayarKeyReleased

    private void BTN_HITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_HITActionPerformed
        // TODO add your handling code here:
        int total = Integer.parseInt(jt_total.getText().trim());
        int bayar = Integer.parseInt(jt_bayar.getText().trim());
        int kembalian = bayar - total;

        txtkembali.setText("" + kembalian);
    }//GEN-LAST:event_BTN_HITActionPerformed

    private void CB_TGLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CB_TGLMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_CB_TGLMouseClicked

    private void JT_TGLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_TGLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_TGLActionPerformed

    private void BTN_TrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_TrsActionPerformed
        // TODO add your handling code here:
        String logic = BTN_Trs.getText();
        if (logic.equals("Transaksi Baru")) {
            baru();
        } else {
            batalbaru();
        }
        bersih();
    }//GEN-LAST:event_BTN_TrsActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        try {
            int baris = jTable1.getSelectedRow();//mengambil urutan baris dari table yang ada
            JT_TRANSAKSI.setText(jTable1.getValueAt(baris, 0).toString());
            JT_TGL.setText(jTable1.getValueAt(baris, 1).toString());
            txt_kode.setText(jTable1.getValueAt(baris, 2).toString());
            JT_NAMABARANG.setText(jTable1.getValueAt(baris, 3).toString());
            JT_HARGABARANG.setText(jTable1.getValueAt(baris, 4).toString());
            JT_JUMLAHBELI.setText(jTable1.getValueAt(baris, 5).toString());
            txtsub.setText(jTable1.getValueAt(baris, 6).toString());
            jt_total.setText(jTable1.getValueAt(baris, 6).toString());
            jt_bayar.setText(jTable1.getValueAt(baris, 7).toString());
            txtkembali.setText(jTable1.getValueAt(baris, 8).toString());

            tombolon();
        } catch (Exception e) {
            System.err.println("Error : " + e);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void CB_TGLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_TGLActionPerformed
        // TODO add your handling code here:
        String tampilan = "dd-MM-yyy";
        SimpleDateFormat format = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(format.format(CB_TGL.getDate()));
        JT_TGL.setText(tanggal);

    }//GEN-LAST:event_CB_TGLActionPerformed

    private void CB_TGLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CB_TGLMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_TGLMousePressed

    private void CB_TGLDateChanged(org.freixas.jcalendar.DateEvent evt) {//GEN-FIRST:event_CB_TGLDateChanged
        // TODO add your handling code here:
        String tampilan = "dd-MM-yyy";
        SimpleDateFormat format = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(format.format(CB_TGL.getDate()));
        JT_TGL.setText(tanggal);
    }//GEN-LAST:event_CB_TGLDateChanged

    private void JT_TRANSAKSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JT_TRANSAKSIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JT_TRANSAKSIActionPerformed

    private void BTN_CETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CETActionPerformed
        // TODO add your handling code here:
        String tanggal = JT_TGL.getText();
        String namabarang = JT_NAMABARANG.getText();
        String harga = JT_HARGABARANG.getText();
        String jumlahbeli = JT_JUMLAHBELI.getText();
        String total = jt_total.getText();
        String bayar = jt_bayar.getText();
        String kembalian = this.txtkembali.getText();
        koneksi kk = new koneksi();
        kk.koneksiDatabase();

        JTA_Hasil.setText("    NOTA TRANSAKSI \n\nTanggal\t:" + tanggal + "\nNama Barang\t:" + namabarang + "\nHargaBarang\t:" + harga
                + "\nJumlah Beli\t:" + jumlahbeli + "\nTotal Beli\t:" + total + "\nBayar\t:" + bayar + "\nKembalian\t:"
                + kembalian);
        
    }//GEN-LAST:event_BTN_CETActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_BER;
    private javax.swing.JButton BTN_CET;
    private javax.swing.JButton BTN_HAP;
    private javax.swing.JButton BTN_HIT;
    private javax.swing.JButton BTN_KEL;
    private javax.swing.JButton BTN_SIM;
    private javax.swing.JButton BTN_Trs;
    private javax.swing.JButton BTN_UB;
    private javax.swing.JComboBox<String> CB_KODE;
    private org.freixas.jcalendar.JCalendarCombo CB_TGL;
    private javax.swing.JTextArea JTA_Hasil;
    private javax.swing.JTextField JT_HARGABARANG;
    private javax.swing.JTextField JT_JUMLAHBELI;
    private javax.swing.JTextField JT_NAMABARANG;
    private javax.swing.JTextField JT_TGL;
    private javax.swing.JTextField JT_TRANSAKSI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jt_bayar;
    private javax.swing.JTextField jt_total;
    private javax.swing.JLabel txt_kode;
    private javax.swing.JLabel txtkembali;
    private javax.swing.JLabel txtkembali1;
    private javax.swing.JLabel txtsub;
    private javax.swing.JLabel txtsub1;
    // End of variables declaration//GEN-END:variables
}
